server:
  port: 8080
  servlet:
    context-path: /


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mallX?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver


