server:
  port: 8080
  servlet:
    context-path: /mallX


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mallX?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    # springboot 默认连接池 hikari 配置
    hikari:
      # 最小连接数
      minimum-idle: 5
      connection-test-query: select 1 from dual
      # 最大连接池梳理，默认10
      maximum-pool-size: 20
      # 开启自动提交
      auto-commit: true
      # 最长多久空闲释放连接，默认10分钟，
      idle-timeout: 30000
      pool-name: HikariCP
      # 连接最长存活时间毫秒，默认30分钟
      max-lifetime: 60000
      # 等待超时时间，默认30秒
      connection-timeout: 30000




mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  # 设置扫描的 mapper.xml
  mapper-locations:
    - classpath:mapper/*.xml

pagehelper:
  auto-dialect: true
  helper-dialect: mysql
  reasonable: true
  params: count=countSql

logging:
  level:
    com.kubertX.springboot.action.orm.mybatis.mapper: trace


# swagger 配置
springfox:
  documentation:
    # 是否启用Swagger扫描代码生成文档
    enabled: true
    open-api:
      # 是否启用Swagger的open-api
      enabled: false
    swagger-ui:
      # 是否启用Swagger的Web UI
      enabled: true
      # 配置文档基础路径，此时路径为：/doc/swagger-ui/index.html
      base-url: /doc